function [ osci_type, dam_size, slope, intercept] = import_conf(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CONF0 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a cell array.
%
%  CONF0 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  conf0 = importfile("/Users/martazaniolo/OneDrive - Politecnico di Milano/Mwache/optimize_oscillations_noOp/configuration_files/conf0.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Sep-2022 15:35:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", " "];

% Specify column names and types
opts.VariableNames = ["osci_type", "sm"];
opts.VariableTypes = ["char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["osci_type", "sm"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["osci_type", "sm"], "EmptyFieldRule", "auto");

% Import the data
conf0 = readtable(filename, opts);

%% Convert to output type
conf0 = table2cell(conf0);
numIdx = cellfun(@(x) ~isnan(str2double(x)), conf0);
conf0(numIdx) = cellfun(@(x) {str2double(x)}, conf0(numIdx));

osci_type = conf0{1,2};
dam_size = conf0{2,2};
slope = conf0{3,2};
intercept = conf0{4,2};


end



